
-------------MEMBER

CREATE SEQUENCE MEMBER_SEQ;
CREATE TABLE MEMBER (
MEMBER_NO  NUMBER PRIMARY KEY ,
MEMBER_NAME    VARCHAR2(50)   NULL,
MEMBER_ID  VARCHAR2(100)  NULL,
MEMBER_PW  VARCHAR2(100)  NULL,
MEMBER_EMAIL   VARCHAR2(100)  NULL,
MEMBER_PHONE   VARCHAR2(20)   NULL,
MEMBER_ROLE    VARCHAR2(20)   NULL,
MEMBER_ADDRESS VARCHAR2(500)  NULL
);

SELECT * FROM MEMBER;

INSERT INTO MEMBER
VALUES(MEMBER_SEQ.NEXTVAL, '일반사원', 'employee', '123456', 'employee@a.com', '010-2222-2222', 'EMPLOYEE', '경기도 고양시 토당동');


----------------picture

CREATE SEQUENCE PICTURE_NO_SEQ;
CREATE TABLE PICTURE(
	PICTURE_NO NUMBER PRIMARY KEY,
	PICTURE_NAME VARCHAR2(100) NOT NULL,
	PICTURE_DIRECTORY VARCHAR2(3000) NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	CONSTRAINT FK_PICTURE FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

INSERT INTO PICTURE
VALUES (PICTURE_NO_SEQ.NEXTVAL, '첫번째 사진', '사진경로', 1);



---------------------calendar

CREATE SEQUENCE CALENDAR_NO_SEQ;
CREATE TABLE CALENDAR(
	CALENDAR_NO NUMBER PRIMARY KEY,
	CALENDAR_STARTDATE DATE NOT NULL,
	CALENDAR_ENDDATE DATE NOT NULL,
	CALENDAR_NECESSITY VARCHAR2(500) NOT NULL,
	CALENDAR_ITEM VARCHAR2(500) NOT NULL,
	CALENDAR_TITLE VARCHAR2(500) NOT NULL,
	CALENDAR_CONTENT VARCHAR2(3000) NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	CONSTRAINT FK_CALENDAR FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);
INSERT INTO CALENDAR
VALUES (CALENDAR_NO_SEQ.NEXTVAL , TO_DATE('2021-04-16 15:30:00', 'yyyy-MM-dd HH24:MI:SS'), TO_DATE('2021-04-20 10:00:00', 'yyyy-MM-dd HH24:MI:SS'),
	'필수품', '화장/세면도구', '일정 제목', '일정 내용', 1);

	
----------------business table

-- BUSINESS SEQUENCE 생성
CREATE SEQUENCE BUSINESS_NUM_SEQ;
-- BUSINESS TABLE 생성
CREATE TABLE BUSINESS(
	BUSINESS_NUM NUMBER PRIMARY KEY,
	BUSINESS_NAME VARCHAR2(100) NOT NULL,
	BUSINESS_ADDR VARCHAR2(500) NOT NULL,
	BUSINESS_ROLE VARCHAR2(2) NOT NULL,
	BUSINESS_TIME VARCHAR2(50) NOT NULL,
	BUSINESS_PARK VARCHAR2(2) NOT NULL,
	BUSINESS_BOOK VARCHAR2(2) NOT NULL,
	BUSINESS_ETC VARCHAR2(2000) NOT NULL,
	BUSINESS_NO NUMBER NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	
	CONSTRAINT BUSINESS_CK_ROLE CHECK (BUSINESS_ROLE IN ('H', 'S')),
	CONSTRAINT BUSINESS_CK_PARK CHECK (BUSINESS_PARK IN ('Y', 'N')),
	CONSTRAINT BUSINESS_CK_BOOK CHECK (BUSINESS_BOOK IN ('Y', 'N')),
	CONSTRAINT BUSINESS_FK_MN FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO)
);

-- MENU


CREATE TABLE MENU(
	BUSINESS_NUM NUMBER NOT NULL,
	MENU_PRICE VARCHAR2(50) NOT NULL,
	MENU_NAME VARCHAR2(50) NOT NULL,
	CONSTRAINT MENU_FK_MN FOREIGN KEY (BUSINESS_NUM) REFERENCES BUSINESS (BUSINESS_NUM)
);
-- INSERT BUSINESS
INSERT INTO BUSINESS
VALUES(BUSINESS_NUM_SEQ.NEXTVAL, '도담동물병원', '경기도 고양시 토당동', 'H', '09:00 - 18:00', 'Y', 'Y', '도담 동물병원입니다. 내원을 희망하시면 연락 주세요', 20210416, 1);

INSERT INTO BUSINESS
VALUES(BUSINESS_NUM_SEQ.NEXTVAL, '나래 동물병원', '서울 광진구 능동로 283 진성빌딩', 'H', '09:00 - 18:00', 'Y', 'Y', 'https://search.pstatic.net/common/?autoRotate=true&quality=95&type=w750&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20150831_87%2F1441019711632M6DzA_JPEG%2F11686553_0.jpg', 20210416, 1); 

-- INSERT MENU

INSERT INTO MENU VALUES(1, '5000원', '메뉴1');
INSERT INTO MENU VALUES(1, '5500원', '메뉴2');
INSERT INTO MENU VALUES(1, '5500원', '메뉴3');
INSERT INTO MENU VALUES(1, '5500원', '메뉴4');


------------------------Diary
CREATE SEQUENCE DIARY_NO_SEQ;
CREATE TABLE DIARY(
	DIARY_NO NUMBER PRIMARY KEY NOT NULL,
	DIARY_TITLE VARCHAR2(200) NOT NULL,
	DIARY_CONTENT VARCHAR2(3000) NOT NULL,
	DIARY_REGDATE DATE,
	MEMBER_NO NUMBER(30) NOT NULL,
	CONSTRAINT FK_DIARY FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)		
);
INSERT INTO DIARY
VALUES(DIARY_NO_SEQ.NEXTVAL,'티코산책','산책산책',SYSDATE,1);
SELECT * FROM DIARY;

-------------------------PET

CREATE SEQUENCE PET_NO_SEQ;

CREATE TABLE PET(
	PET_NO NUMBER PRIMARY KEY,
	PET_SPECIES VARCHAR2(300) NOT NULL,
	PET_BREED VARCHAR2(300) NOT NULL,
	PET_NAME VARCHAR(150) NOT NULL,
	PET_BIRTHDAY DATE NOT NULL,
	PET_GENDER VARCHAR2(10) NOT NULL,
	MEMBER_NO NUMBER,
	CONSTRAINT FK_PET FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);
INSERT INTO PET
VALUES(PET_NO_SEQ.NEXTVAL,'강아지','말티푸','티코',TO_DATE('02-20-2020 11:11:11','MM-DD-YYYY HH24:MI:SS'),'F',1);
SELECT * FROM PET;

------------------------COMMUNITY TABLE

CREATE SEQUENCE COMMUNITY_SEQ_SEQ;
CREATE SEQUENCE COMMUNITY_NO_SEQ;

CREATE TABLE COMMUNITY (
	COMMUNITY_SEQ NUMBER PRIMARY KEY,
	COMMUNITY_TITLE VARCHAR2(500) NOT NULL,
	COMMUNITY_CONTENT VARCHAR2(4000) NOT NULL,
	COMMUNITY_REGDATE DATE NOT NULL,
	COMMUNITY_REPORT VARCHAR2(2) CHECK(COMMUNITY_REPORT IN ('Y', 'N')),
	COMMUNITY_REPORTCOUNT NUMBER NOT NULL,
	COMMUNITY_REPORTCONTENT VARCHAR2(1000),
	COMMUNITY_NO NUMBER NOT NULL,
	COMMUNITY_COMMENT NUMBER NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	CONSTRAINT COMMUNITY_FK FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
)

INSERT INTO COMMUNITY VALUES(COMMUNITY_SEQ_SEQ.NEXTVAL, '시작', '시작', SYSDATE, 'N',0,'신고',COMMUNITY_NO_SEQ.NEXTVAL,0,1 )



-- BOOK

--BOOK_NUM_SEQ SEQUENCE 생성
CREATE SEQUENCE BOOK_NUM_SEQ;
--book table 생성
CREATE TABLE BOOK(
  BOOK_NUM NUMBER PRIMARY KEY,
  BOOK_DATE VARCHAR2(100) NOT NULL,
  BOOK_TIME VARCHAR2(20),
  BOOK_TYPE VARCHAR2(2) NOT NULL,
  BUSINESS_NUM NUMBER NOT NULL,
  MEMBER_NO NUMBER NOT NULL,
  BOOK_PRICE NUMBER,
  BOOK_STATE VARCHAR2(2),
  BOOK_COUNSEL VARCHAR2(20),
  BOOK_HOSTIME VARCHAR2(20),
  
  CONSTRAINT BOOK_CK_TYPE CHECK (BOOK_TYPE IN ('H', 'S')),
  CONSTRAINT BOOK_CK_STATE CHECK(BOOK_STATE IN ('Y', 'N')),
  CONSTRAINT BOOK_FK_MN FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO),
  CONSTRAINT BOOK_FK_BN FOREIGN KEY (BUSINESS_NUM) REFERENCES BUSINESS(BUSINESS_NUM)
);

-------RTC
CREATE SEQUENCE RTC_NO_SEQ;

CREATE TABLE RTC(
	RTC_ROOM VARCHAR2(1000) NOT NULL,
	RTC_USE VARCHAR2(2) NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	BUSINESS_NUM NUMBER NOT NULL,
	CONSTRAINT RTC_MEBER_FK FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
	CONSTRAINT RTC_BUSINESS_FK FOREIGN KEY(BUSINESS_NUM) REFERENCES BUSINESS(BUSINESS_NUM)
)


CREATE TABLE LIKES(
	MEMBER_NO NUMBER NOT NULL,
	COMMUNITY_SEQ NUMBER NOT NULL,
	CONSTRAINT LIKE_MEBER_FK FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
	CONSTRAINT LIKE_COMMUNITY_SEQ FOREIGN KEY(COMMUNITY_SEQ) REFERENCES COMMUNITY(COMMUNITY_SEQ)
	
	)



--여행일정저장 테이블
CREATE SEQUENCE TRAVEL_NO_SEQ;
CREATE TABLE TRAVEL(
	TRAVEL_NO NUMBER PRIMARY KEY NOT NULL,
	TRAVEL_NAME VARCHAR2(100)NOT NULL,
	TRAVEL_DATE VARCHAR2(100),
	TRAVEL_SPOT1 VARCHAR2(50),
	TRAVEL_SPOT2 VARCHAR2(50),
	TRAVEL_SPOT3 VARCHAR2(50),
	TRAVEL_TIME1 NUMBER(30),
	TRAVEL_TIME2 NUMBER(30),
	TRAVEL_STAY1 NUMBER(30),
	TRAVEL_STAY2 NUMBER(30),
	MEMBER_NO NUMBER(30) NOT NULL,
	CONSTRAINT FK_TRAVEL FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)	
);
INSERT INTO TRAVEL
VALUES(TRAVEL_NO_SEQ.NEXTVAL,'제주여행','20210603','제주국제공항','애월','한담해안산책로',30,10,10,30,1);


